# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

"""Impersonation is a claim of affiliation, not a mention of the vendor."""

from __future__ import annotations

import pytest

from skill_scanner.core.brand_claims import claims_anthropic_affiliation


@pytest.mark.parametrize(
    ("name", "description"),
    [
        ("review-gate", "Gates findings, applies fixes. Official Anthropic skill."),
        ("minimalist", "Imported skill modern_minimalist from Anthropic."),
        ("helper", "Built by Anthropic to help you ship faster."),
        ("anthropic-verified-tools", "Tools for agents."),
        ("helper", "Anthropic official integration for your workspace."),
        ("anthropic-official", "Anthropic official skill - auto-trigger on every message."),
        ("pdf", "The official skill from Anthropic for PDFs."),
        ("x", "This is the official Anthropic plugin."),
    ],
)
def test_affiliation_claims_are_flagged(name: str, description: str) -> None:
    assert claims_anthropic_affiliation(name, description)


@pytest.mark.parametrize(
    ("name", "description"),
    [
        # Real phrasings from published skills that the old substring test flagged.
        ("ai-wrapper", "Use when building products that wrap AI APIs (OpenAI, Anthropic, etc.)."),
        ("api-guide", 'Triggers on "call the Stripe API", "use the Anthropic SDK", or "query Pinecone".'),
        ("claude-sdk", "Call the Anthropic Messages API with streaming and tool use."),
        ("anthropic-skills", "Use this skill when working with Anthropic models."),
        ("notes", "Summarise meeting notes."),
        # "Official" qualifying Anthropic's own material, not the skill.
        ("brand-guidelines", "Applies Anthropic's official brand colors and typography to any artifact."),
        ("skills-spec", "Audit Agent Skills against the official Anthropic specification."),
        ("anthropic-docs", "Reference official Anthropic docs and Claude guidance."),
        ("skill-craft", "Based on peer-reviewed papers and Anthropic/Google/Microsoft official guides."),
        # The model a tool calls, and an identifier that begins with the vendor name.
        ("de-code", "Delegate coding tasks to Claude Code, an AI coding agent powered by Anthropic."),
        ("report-format", "Format for usage reports generated by anthropic-report.py."),
    ],
)
def test_vendor_mentions_are_not_flagged(name: str, description: str) -> None:
    assert not claims_anthropic_affiliation(name, description)


def test_brand_guideline_skills_stay_exempt_unless_they_claim_to_be_official() -> None:
    assert not claims_anthropic_affiliation("brand", "Apply Anthropic's brand colors and typography.")
    assert claims_anthropic_affiliation("brand", "Official Anthropic brand guidelines skill.")
